services:
  api:
    container_name: "job_storage_api"
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - job_storage

  db:
    container_name: "job_storage_db"
    image: postgres:17
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - job_storage

networks:
  job_storage:
    driver: bridge
