"""empty message

Revision ID: 5647b1d1a1a9
Revises: cda9c4317c06
Create Date: 2024-11-17 15:55:45.390398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5647b1d1a1a9'
down_revision: Union[str, None] = 'cda9c4317c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('key_skills', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('vacancy', 'skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('vacancy', 'key_skills')
    # ### end Alembic commands ###
