"""empty message

Revision ID: cda9c4317c06
Revises: 18f7f31a135d
Create Date: 2024-11-11 13:58:51.851030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cda9c4317c06'
down_revision: Union[str, None] = '18f7f31a135d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('work_mode', sa.String(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('links', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vacancy', sa.Column('source_name', sa.String(), nullable=True))
    op.add_column('vacancy', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('vacancy', sa.Column('area', sa.String(), nullable=True))
    op.add_column('vacancy', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.drop_column('vacancy', 'source')
    op.drop_column('vacancy', 'key_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('key_skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('vacancy', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vacancy', 'published_at')
    op.drop_column('vacancy', 'area')
    op.drop_column('vacancy', 'skills')
    op.drop_column('vacancy', 'source_name')
    op.drop_table('user')
    op.drop_table('resume')
    # ### end Alembic commands ###
